#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_TERMIOS_H 1
#define HAVE_CFMAKERAW 1
#define HAVE_SYS_IOCTL_H 1
#define HAVE_RB_CHECK_HASH_TYPE 1
#define HAVE_RB_IO_GET_WRITE_IO 1
#define HAVE_RB_CLOEXEC_OPEN 1
#define HAVE_RB_SCAN_ARGS_OPTIONAL_HASH 1
#endif
